# Copyright (C) CampusIoT,  - All Rights Reserved
# Written by CampusIoT Dev Team, 2016-2018

version: "2"

services:

  # https://github.com/PeterGrace/opentsdb-docker/blob/master/docker-compose.yml
  opentsdb:
    image: petergrace/opentsdb-docker:latest
    environment:
      - WAITSECS=30
    ports:
      - 4242:4242
      - 60030:60030
    restart: unless-stopped
    labels:
      NAME: "opentsdb"
