{
 "title": "Gateways",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Gateways uplink throughtput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "mac" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stat",
     "query": "SELECT sum(\"rxPacketsReceivedOK\") FROM \"stat\" WHERE $timeFilter GROUP BY time($__interval), \"mac\" fill(null)",
     "select": [
      [
       { "params": [ "rxPacketsReceivedOK" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Datarate heatmap",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "dr" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rx",
     "select": [
      [
       { "params": [ "size" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Frequencies JREQ-REJOIN (nb. frames/min)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "frequency" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rx",
     "select": [
      [
       { "params": [ "size" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "frametype", "operator": "=", "value": "jreq" },
      { "condition": "OR", "key": "frametype", "operator": "=", "value": "rejoin" }
     ]
    }
   ]
  },
  {
   "title": "Frequencies DTUP (nb. frames/min)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "frequency" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rx",
     "select": [
      [
       { "params": [ "size" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "frametype", "operator": "=", "value": "dtup" }
     ]
    }
   ]
  },
  {
   "title": "Frequencies JREQ-REJOIN (nb. frames/min)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "frequency" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rx",
     "query": "SELECT count(\"size\") FROM \"rx\" WHERE (\"operator\" != 'undefined' AND \"frametype\" = 'dtup') AND $timeFilter GROUP BY time($__interval), \"operator\" fill(null)",
     "select": [
      [
       { "params": [ "size" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "frametype", "operator": "=", "value": "jreq" },
      { "condition": "OR", "key": "frametype", "operator": "=", "value": "rejoin" }
     ]
    }
   ]
  },
  {
   "title": "Frequencies DTUP (nb. frames/min)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "frequency" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rx",
     "query": "SELECT count(\"size\") FROM \"rx\" WHERE (\"operator\" != 'undefined' AND \"frametype\" = 'dtup') AND $timeFilter GROUP BY time($__interval), \"operator\" fill(null)",
     "select": [
      [
       { "params": [ "toa" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "frametype", "operator": "=", "value": "dtup" }
     ]
    }
   ]
  },
  {
   "title": "Dutycycle g1",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "mac" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tx",
     "query": "SELECT count(\"size\") FROM \"rx\" WHERE (\"operator\" != 'undefined' AND \"frametype\" = 'dtup') AND $timeFilter GROUP BY time($__interval), \"operator\" fill(null)",
     "select": [
      [
       { "params": [ "toa" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "subband", "operator": "=", "value": "g1" }
     ]
    }
   ]
  },
  {
   "title": "Dutycycle g3",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "mac" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tx",
     "query": "SELECT count(\"size\") FROM \"rx\" WHERE (\"operator\" != 'undefined' AND \"frametype\" = 'dtup') AND $timeFilter GROUP BY time($__interval), \"operator\" fill(null)",
     "select": [
      [
       { "params": [ "toa" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "subband", "operator": "=", "value": "g3" }
     ]
    }
   ]
  },
  {
   "title": "Dutycycle g",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "mac" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tx",
     "query": "SELECT count(\"size\") FROM \"rx\" WHERE (\"operator\" != 'undefined' AND \"frametype\" = 'dtup') AND $timeFilter GROUP BY time($__interval), \"operator\" fill(null)",
     "select": [
      [
       { "params": [ "toa" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "subband", "operator": "=", "value": "g" }
     ]
    }
   ]
  }
 ]
}